### ISSUE TITLE
Report a `cursor` bug

### ISSUE THREAD

**Issue by bingbig** [eatonphil/gosql#1]
Hi, It's an awesome project!  But panic throw out when I run the code, it seems to be a problem caused by `cursor++`  @L413. Maybe you have fixed it already. 

https://github.com/eatonphil/gosql/blob/6a788b65f6842344d79166f61a46f908e95dc7d5/parser.go#L402-L414

Looking forward to view more commits.

**Comment by eatonphil** [comment]
Hey! Could you include the full program you ran and the stacktrace?

**Comment by bingbig** [comment]
```sh
$ go run cmd/libraryexample/main.go 
panic: Failed to parse, expected statement

goroutine 1 [running]:
main.main()
        /Users/liub/golang/gosql/cmd/libraryexample/main.go:17 +0x742
exit status 2

**Comment by eatonphil** [comment]
Gotcha, you were right. The extra cursor update on line 413 causes multiple statements to be parsed incorrectly. Fixed in https://github.com/eatonphil/gosql/commit/b1e42e09d9d230648edb59c26dd668b2a37bdc8f.

**Comment by eatonphil** [comment]
Thank you!
