### ISSUE TITLE
String style question :)

### ISSUE THREAD

**Issue by justinclift** [eatonphil/gosql#19]
Looking through the code, there's a few uses of strings like [`"\\d"`](https://github.com/eatonphil/gosql/blob/master/cmd/main.go#L214), [`"\\p"`](https://github.com/eatonphil/gosql/blob/master/cmd/main.go#L221) and similar.

Is there a reason for choosing the double quoted string style over backticks (eg `` `\d` ``), or is it just a personal preference thing? :smile:

**Comment by eatonphil** [comment]
Nope! I keep forgetting about some nice places to use backtick strings. Feel free to make a PR if you'd like.

**Comment by justinclift** [comment]
No worries. :smile:

Generally, I'd make a PR to adjust things, but well... repo owned by Oracle, and I'm not really inclined to do anything that could help Oracle, even unintentionally. :wink:

**Comment by eatonphil** [comment]
This is not an Oracle repo, this is a personal project.

**Comment by justinclift** [comment]
Your employment agreement with them **doesn't** give them ownership of things you do "after hours"?

Asking just to be sure, as for many companies it does and people just have checked. :frowning:

That being said, if you're sure then I'm happy to contribute here.

**Comment by eatonphil** [comment]
The repository license is MIT in my name. That should be sufficient proof of ownership. If that ever changes, the repo could be forked before then to continue with the open license.

**Comment by justinclift** [comment]
Sorry.  I really am, as this project looks very interesting to me.  I'm working through what it would take to create a ~simple (famous last words) SQLite parser limited to SELECT statements and this is right in line with that. :smile:

But, with your employer being Oracle (famously litigation happy), I just can't take the chance.
