### ISSUE TITLE
3 questions

### ISSUE THREAD

**Issue by gitmko0** [eatonphil/gosql#22]
1. production ready? use case?
2. secondary unique key index possible?
   is text search possible?
3. benchmark compared with postgres / mysql?

great work by the way! keep it up. will use it. a lot of potential.

**Comment by eatonphil** [comment]
Hey, I try to keep issues for bug reports and not questions. Feel free to email me with further questions.

1. Nope, you'll see very few tests and very little supported syntax. Could be used as base to build further. Also has no disk-backed backend, only in-memory currently. So at best may be used for some simple unit tests.
2. Multiple keys are supported but not multi-column keys.
3. Nope.
