### ISSUE TITLE
Blog update

### ISSUE THREAD

**Issue by taybart** [eatonphil/gosql#23]
I was planning on following [this](https://notes.eatonphil.com/database-basics-a-database-sql-driver.html), however, it seems its pretty far behind and has some issues with the code in the blog. Is it possible to get it updated to master? If not, could we create a branch where the simplicity of the blog is captured?

Thanks for the article, I always love a lexing walkthrough I would love to follow it through code!

**Comment by eatonphil** [comment]
Hey! Great to see folks interested in working through the posts! Unfortunately a product of the way I've set up my posts is that they aren't easy to follow along individually. The only way I can imagine someone following along is by going through each post.

In the future I'm thinking of embedding runnable code (a la replit) to make it so I don't have to maintain three versions of things (1) the blog, 2) the real project, 3) the project solely as described in the blog [in case I haven't yet blogged through additions made to the real project]). In the meantime keeping up three projects like that is too big a pain.

Let me know though if you have a hard time getting through the actual blogs. Each post should compile and should build off only the last post. Let me know if that's not the case.
