### ISSUE TITLE
will porting to lmdb / boltdb backend be on the roadmap?

### ISSUE THREAD

**Issue by hiqsociety** [eatonphil/gosql#26]
will porting to lmdb / boltdb backend be on the roadmap?

**Comment by eatonphil** [comment]
Hey! The big blocker at the moment preventing easy introduction of a disk based solution is that most disk storage libraries deal with transactions and that's not something gosql knows about yet.

So first I have to get to transactions and then disk storage should be easier.

That said, I try to keep all issues for bug reports only so if you have more questions please just email me!
